config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'job_recommendations', to: 'refugees#job_recommendations'
  get 'my_applications', to: 'refugees#my_applications'

  post 'apply', to: 'refugees#apply'


  resources :refugees
  resources :organizations
  resources :jobs, except: [:new]


  get 'settings', to: 'pages#settings'

  # Sessions
  post 'login-org', to: 'sessions#login_org'
  post 'login-ref', to: 'sessions#login_ref'
  delete 'logout', to: 'sessions#logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  has_many :refugees
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :jobs_skills_links
  has_many :skills, through: :jobs_skills_links

  has_many :refugees_jobs_links
  has_many :refugees, through: :refugees_jobs_links

  belongs_to :organization
end

app/models/jobs_skills_link.rb
class JobsSkillsLink < ActiveRecord::Base
  belongs_to :job
  belongs_to :skill
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :refugees_languages_links
  has_many :refugees, through: :refugees_languages_links
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :jobs

  mount_uploader :avatar, AvatarUploader

  has_secure_password
end

app/models/profession.rb
class Profession < ActiveRecord::Base
  has_many :refugees_professions_links
  has_many :refugees, through: :refugees_professions_links
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :issue, polymorphic: true
end

app/models/refugee.rb
class Refugee < ActiveRecord::Base
  has_many :refugees_professions_links
  has_many :professions, through: :refugees_professions_links

  has_many :refugees_languages_links
  has_many :languages, through: :refugees_languages_links4

  has_many :skills_refugees_links
  has_many :skills, through: :skills_refugees_links

  has_many :refugees_jobs_links
  has_many :jobs, through: :refugees_jobs_links

  has_secure_password

  has_one :degree

  mount_uploader :avatar, AvatarUploader
end

app/models/refugees_jobs_link.rb
class RefugeesJobsLink < ActiveRecord::Base
  belongs_to :refugee
  belongs_to :job
end

app/models/refugees_languages_link.rb
class RefugeesLanguagesLink < ActiveRecord::Base
  belongs_to :refugee
  belongs_to :language
end

app/models/refugees_professions_link.rb
class RefugeesProfessionsLink < ActiveRecord::Base
  belongs_to :refugee
  belongs_to :profession
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :jobs_skills_links
  has_many :jobs, through: :jobs_skills_links

  has_many :skills_refugees_links
  has_many :refugees, through: :skills_refugees_links
end

app/models/skills_refugees_link.rb
class SkillsRefugeesLink < ActiveRecord::Base
  belongs_to :skill
  belongs_to :refugee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
    @refugees = @job.refugees
  end

  def create
    skills = params[:job][:skills]
    @job = Job.new(title: params[:job][:title], description: params[:job][:description], expiration_date: params[:job][:expiration_date], location: params[:job][:location])
    @job.organization_id = session[:org_id]

    if @job.save
      skills.each do |s|
        rel = JobsSkillsLink.new(job_id: @job.id, skill_id: s.to_i)
        rel.save
      end

      redirect_to jobs_path
    else

    end

  end

  private
  def jobs_params
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def home
  end

  def index
    @organizations = Organization.all()
  end

  def new
    @organization = Organization.new()
  end

  def edit
    set_organization
  end

  def show
    set_organization
    session[:organization_id] = @organization.id
  end

   def create
    @organization = Organization.new(organization_params)
    if(@organization.save)
        redirect_to organization_path(@organization.id)
    else
        render 'new'
    end
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :contact, :address, :email, :password, :description, :avatar)
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @hide_nav = true
  end

  def settings

  end

end

app/controllers/refugees_controller.rb
class RefugeesController < ApplicationController


private
  def refugee_params
    params.require(:refugee).permit(:name, :birthday, :gender, :nationality, :address, :email, :phone, :additional_info, :degree_id , :password, :avatar)
  end


public
  def index
    @refugees = Refugee.all
  end

  def job_recommendations
    @refugee = Refugee.find(session[:ref_id])
    @skills = @refugee.skills
    @jobs = []
    @skills.each do |u|
      u.jobs.each do |s|
        if !(@jobs.include? s)
          @jobs << s
        end
      end
    end
    render 'jobs/index'
  end

  def apply
    @refugee = RefugeesJobsLink.new(refugee_id: session[:ref_id], job_id: params[:id]);
    @refugee.save
    redirect_to jobs_path
  end

  def new
    @refugee = Refugee.new()
  end

  def create
    @refugee = Refugee.new(refugee_params)
    if @refugee.save
        redirect_to refugees_path
    else
        render 'new'
    end
  end

  def my_applications
    @refugee = Refugee.find(session[:ref_id])
    @applications = @refugee.jobs
  end

  def show
    @refugee = Refugee.find(params[:id])
    session[:refugee_id] = @refugee.id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login_org
    org = Organization.find_by(email: params[:session][:email])

    if org && org.authenticate(params[:session][:password])
      session[:org_id] = org.id
      session[:ref_id] = nil
      redirect_to jobs_path
    end
  end

  def login_ref
    ref = Refugee.find_by(email: params[:session][:email])

    if ref && ref.authenticate(params[:session][:password])
      session[:ref_id] = ref.id
      session[:org_id] = nil
      redirect_to jobs_path
    end
  end

  def logout
    session[:ref_id]
    session[:org_id]
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/_modal_form.html.erb
<div class="modal fade" id="jobModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title" id="myModalLabel">Adicionar Vaga</h2>
      </div>
      <div class="modal-body">
        <%= form_for(:job, :html => {class: "form-horizontal", role: "form"}, url: jobs_path, action: "POST") do |f| %>
          <div class="form-group">
            <div class="col-sm-8 col-sm-offset-2">
              <div class="inner-addon left-addon">
                <div class="input-group">
                  <span class="input-group-addon" id="basic-addon1">
                    <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
                  </span>
                  <%= f.text_field :title, class: "form-control", placeholder: "Job Title" %>
                </div>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-8 col-sm-offset-2">
              <div class="inner-addon left-addon">
                <div class="input-group">
                  <span class="input-group-addon" id="basic-addon1">
                    <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                  </span>
                  <%= f.date_field :expiration_date, class: "form-control", autocomplete: "off" %>
                </div>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-8 col-sm-offset-2">
              <div class="inner-addon left-addon">
                <div class="input-group">
                  <span class="input-group-addon" id="basic-addon1">
                    <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                  </span>
                  <%= f.text_field :location, class: "form-control", placeholder: "Location", autocomplete: "off" %>
                </div>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-8 col-sm-offset-2">
              <div class="inner-addon left-addon">
                <%= f.text_area :description, class: "form-control", placeholder: "Job description", rows: 5 %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-8 col-sm-offset-2">
              <% Skill.all.each do |s| %>
                <%= f.check_box(:skills, { :multiple => true }, s.id, nil) %>
                <label><%= s.name %></label>
              <% end %>
            </div>
          </div>
          <div class="form-group">
            <div class="text-center">
              <%= f.submit("Gravar", class: "btn btn-primary btn-lg") %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="innerStyle">
  <div class="container">
    <!--<h1 align="center" class="sub-title">Organizations</h1>-->
    <div align="center">
      <h1>Available Opportunities</h1>
      <div class="input-group">
        <span class="input-group-addon button" id="basic-addon1">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </span>
        <input type="text" id="search" placeholder="Search" autocomplete="off" class="form-control center-block">
      </div>
    </div>
    <div>
    <br>
    <div class="row">
      <% @jobs.each do |j| %>
            <div class="col-sm-6 col-md-4">
              <div class="thumbnail">
                <%= image_tag "profile.png", class: "list-image" %>
                <div class="caption">
                  <h3 class="text-center"><%= j.title %></h3>
                  <p><strong>Competências:</strong> <% j.skills.each_with_index do |s, idx| %><%= s.name %><%= " &#8226; ".html_safe if idx < j.skills.length - 1%><% end %></p>
                  <div class="text-center">
                    <%= link_to "Ver Detalhes", job_path(j.id), class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="innerStyle">
  <div class="container">
  	<div class="row">
  		<div class="col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
    	 <div class="well profile">
        <div class="col-sm-12">
          <div class="col-xs-12 col-sm-8">
              <h2><%= @job.title %></h2>
              <p><strong>Descrição: </strong><%= @job.description %></p>
              <p><strong>Competências: </strong>
                  <% @job.skills.each do |s| %>
                    <span class="tags"><%= s.name %></span>
                  <% end %>
              </p>
          </div>
          <div class="col-xs-12 col-sm-4 text-center">
              <figure>
                  <%= image_tag "job.png", class: "img-circle img-responsive" %>
              </figure>
          </div>
          <% if session[:ref_id] != nil %>
              <% if !(@refugees.include? Refugee.find(session[:ref_id])) %>
                <div class="text-center">
                    <%= link_to "Apply", apply_path(id: @job.id), class: "btn btn-primary", method: "POST" %>
                </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/organizations/index.html.erb
<div class="innerStyle">
  <div class="container">
    <!--<h1 align="center" class="sub-title">Organizations</h1>-->
    <div align="center">
      <div class="inner-addon left-addon">
        <h1>Organizations</h1>
        <div class="input-group">
          <span class="input-group-addon button" id="basic-addon1">
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </span>
          <input type="text" id="search" placeholder="Search" autocomplete="off" class="form-control center-block">
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <% @organizations.each do |org| %>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <% if org.avatar.url.nil? %>
              <%= image_tag "profile.png", class: "list-image" %>
            <% else %>
              <%= image_tag org.avatar, class: "list-image"%>
            <% end %>
              <div class="caption">
                <h3><%= org.name %></h3>
                <p><strong>Contacto telefónico:</strong> <%= org.contact %></p>
                <p><strong>Email:</strong> <%= org.email %></p>
                <p><strong>Morada:</strong> <%= org.address %></p>
                <div class="text-center">
                  <%= link_to "See profile", organization_path(org.id), class: "btn btn-primary" %>
                </div>
              </div>
          </div>
        </div>
      <% end %>
      <a href="/">Back to Main Page </a>
    </div>
  </div>
</div>

app/views/organizations/new.html.erb
<div class="innerStyle">
    <div class="row">
	    <%= form_for @organization do |f| %>
	    <div class="form-group spacing-bottom">
	        <div class="col-sm-6 col-sm-offset-1.5">
	            <div class="inner-addon left-addon  spacing-top">
	                <div class="input-group">
	                    <span class="input-group-addon" id="basic-addon1">
	                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
	                    </span>
	                    <%= f.text_field :name, class: "form-control", placeholder: "Enter name", autofocus: true %>
	                </div>
	            </div>
	        </div>
	    </div>
	    <div class="form-group spacing-bottom">
	        <div class="col-sm-6 col-sm-offset-1.5">
	            <div class="inner-addon left-addon  spacing-top">
	                <div class="input-group">
	                    <span class="input-group-addon" id="basic-addon1">
	                        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
	                      </span>
	                    <%= f.password_field :password, class: "form-control", placeholder: "Enter password", autocomplete: "off" %>
	                </div>
	            </div>
	        </div>
	    </div>
	    <div class="form-group spacing-bottom">
	        <div class="col-sm-6 col-sm-offset-1.5">
	            <div class="inner-addon left-addon  spacing-top">
	                <div class="input-group">
	                    <span class="input-group-addon" id="basic-addon1">
	                        <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
	                    </span>
	                    <%= f.text_field :contact, class: "form-control", placeholder: "Enter your contact", autocomplete: "off" %>
	                </div>
	            </div>
	        </div>
	    </div>
	     <div class="form-group spacing-bottom">
	        <div class="col-sm-6 col-sm-offset-1.5">
	            <div class="inner-addon left-addon  spacing-top">
	                <div class="input-group">
	                    <span class="input-group-addon" id="basic-addon1">
	                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
	                    </span>
	                    <%= f.text_field :address, class: "form-control", placeholder: "Enter your adress", autocomplete: "off" %>
	                </div>
	            </div>
	        </div>
	    </div>
	     <div class="form-group spacing-bottom">
	        <div class="col-sm-6 col-sm-offset-1.5">
	            <div class="inner-addon left-addon  spacing-top">
	                <div class="input-group">
	                    <span class="input-group-addon" id="basic-addon1">
	                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
	                    </span>
	                    <%= f.email_field :email, class: "form-control", placeholder: "Enter your email", autocomplete: "off" %>
	                </div>
	            </div>
	        </div>
	    </div>
	    <div class="form-group spacing-bottom">
	        <div class="col-sm-6 col-sm-offset-1.5">
	            <div class="inner-addon left-addon  spacing-top">
	                <div class="input-group">
	                    <span class="input-group-addon" id="basic-addon1">
	                        <span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span>
	                    </span>
	                    <%= f.text_field :description, class: "form-control", placeholder: "You can use this field for adding some more info about organization", autocomplete: "off" %>
	                </div>
	            </div>
	        </div>
	    </div>
      <div class="form-group spacing-bottom">
	        <div class="col-sm-6 col-sm-offset-1.5">
	            <div class="inner-addon left-addon  spacing-top">
	                <div class="input-group">
	                    <span class="input-group-addon" id="basic-addon1">
	                        <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>
	                    </span>
                      <%= f.file_field :avatar, required: true %>
	                </div>
	            </div>
	        </div>
	    </div>
    </div>
    <div class="form-group spacing-bottom">
        <div class="col-sm-6 col-sm-offset-1.5">
            <div class="inner-addon left-addon  spacing-top">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">
                        <span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span>
                    </span>
                    <%= f.text_field :description, class: "form-control", placeholder: "You can use this field for adding some more info about organization", autocomplete: "off" %>
                </div>
            </div>
        </div>
    </div>
	    <div class="row">
		    <div class="form-group spacing-top">
		        <div class="text-center">
		            <%= f.submit("Sign Up", class: "btn btn-primary btn-lg") %>
		        </div>
		    </div>
		</div>
	    <% end %>
	</div>
</div>

app/views/organizations/show.html.erb
<div class="innerStyle">
  <div class="col-md-4 col-md-offset-4 spacing-top">
    <div class="thumbnail">
      <% if @organization.avatar.url.nil? %>
        <%= image_tag "profile.png", class: "list-image" %>
      <% else %>
        <%= image_tag @organization.avatar, class: "list-image"%>
      <% end %>
        <div class="caption">
          <h3 class="text-center"><%= @organization.name %></h3>
          <p><strong>Contacto telefónico:</strong> <%= @organization.contact %></p>
          <p><strong>Email:</strong> <%= @organization.email %></p>
          <p><strong>Morada:</strong> <%= @organization.address %></p>
        </div>
    </div>
  </div>
</div>

app/views/refugees/index.html.erb
<div class="innerStyle">
  <div class="container">
    <!--<h1 align="center" class="sub-title">Organizations</h1>-->
    <div align="center">
      <div class="inner-addon left-addon">
        <div class="input-group">
          <span class="input-group-addon button" id="basic-addon1">
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </span>
          <input type="text" id="search" placeholder="Search" autocomplete="off" class="form-control center-block">
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <% @refugees.each do |ref| %>
            <div class="col-sm-6 col-md-4">
              <div class="thumbnail">
                <% if ref.avatar.url.nil? %>
                  <%= image_tag "profile.png", class: "list-image" %>
                <% else %>
                  <%= image_tag ref.avatar, class: "list-image"%>
                <% end %>
                <div class="caption">
                  <p><strong>Nome:</strong> <%= ref.name %></p>
                  <p><strong>Nacionalidade:</strong> <%= ref.nationality %></p>
                  <div class="text-center">
                    <%= link_to "See profile", refugee_path(ref.id), class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
          </div>
      <% end %>
      <a href="/jobs">Back to Jobs Page </a>
    </div>
  </div>
</div>

app/views/refugees/my_applications.html.erb
<div class="innerStyle">
  <div class="container">
    <!--<h1 align="center" class="sub-title">Organizations</h1>-->
    <div align="center">
      <h1>My Applications</h1>
      <div class="input-group">
        <span class="input-group-addon button" id="basic-addon1">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </span>
        <input type="text" id="search" placeholder="Search" autocomplete="off" class="form-control center-block">
      </div>
    </div>
    <div>
    <br>
    <div class="row">
      <% @applications.each do |j| %>
            <div class="col-sm-6 col-md-4">
              <div class="thumbnail">
                <%= image_tag "profile.png", class: "list-image" %>
                <div class="caption">
                  <h3 class="text-center"><%= j.title %></h3>
                  <p><strong>Competências:</strong> <% j.skills.each_with_index do |s, idx| %><%= s.name %><%= " &#8226; ".html_safe if idx < j.skills.length - 1%><% end %></p>
                  <div class="text-center">
                    <%= link_to "Ver Detalhes", job_path(j.id), class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/refugees/new.html.erb
<div class="innerStyle">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <%= form_for @refugee do |f| %>
                <div class="form-group spacing-bottom">
                    <div class="col-sm-6 col-sm-offset-1.5">
                        <div class="inner-addon left-addon  spacing-top">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">
                                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                </span>
                                <%= f.text_field :name, class: "form-control", placeholder: "Enter name", autofocus: true %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group spacing-bottom">
                    <div class="col-sm-6 col-sm-offset-1.5 col-tm-offset-2">
                        <div class="inner-addon left-addon spacing-top">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">
                                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                                  </span>
                                <%= f.password_field :password, class: "form-control", placeholder: "Enter password", autocomplete: "off" %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group spacing-bottom">
                    <div class="col-sm-6 col-sm-offset-1.5">
                        <div class="inner-addon left-addon spacing-top">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">
                                    <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                                </span>
                                <%= f.date_field :birthday, class: "form-control", placeholder: "Enter birth date", autocomplete: "off" %>
                            </div>
                        </div>
                    </div>
                </div>
                 <div class="form-group spacing-bottom">
                    <div class="col-sm-6 col-sm-offset-1.5">
                        <div class="inner-addon left-addon spacing-top">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">
                                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                </span>
                                <label> Male </label><%= f.radio_button :gender, "0" %>
                                <label> Female </label><%= f.radio_button :gender, "1" %>
                            </div>
                        </div>
                    </div>
                </div>
                 <div class="form-group spacing-bottom">
                    <div class="col-sm-6 col-sm-offset-1.5">
                        <div class="inner-addon left-addon spacing-top">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">
                                    <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
                                </span>
                                <%= f.text_field :nationality, class: "form-control", placeholder: "Enter your nationality", autocomplete: "off" %>
                            </div>
                        </div>
                    </div>
                </div>
                 <div class="form-group spacing-bottom">
                    <div class="col-sm-6 col-sm-offset-1.5">
                        <div class="inner-addon left-addon  spacing-top">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">
                                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                                </span>
                                <%= f.text_field :address, class: "form-control", placeholder: "Enter your adress", autocomplete: "off" %>
                            </div>
                        </div>
                    </div>
                </div>
                 <div class="form-group spacing-bottom">
                    <div class="col-sm-6 col-sm-offset-1.5">
                        <div class="inner-addon left-addon  spacing-top">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">
                                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                                </span>
                                <%= f.email_field :email, class: "form-control", placeholder: "Enter your email", autocomplete: "off" %>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="form-group spacing-bottom">
                    <div class="col-sm-6 col-sm-offset-1.5">
                        <div class="inner-addon left-addon  spacing-top">
                            <div class="input-group">
                                <div class="col-sm-8 well">
                                <h2>
                                Skills
                                </h2>
                                  <% Skill.all.each do |s| %>
                                    <%= f.check_box(:skills, { :multiple => true }, s.id, nil) %>
                                    <label><%= s.name %></label>
                                  <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group spacing-bottom">
                    <div class="col-sm-6 col-sm-offset-1.5">
                        <div class="inner-addon left-addon  spacing-top">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">
                                    <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
                                </span>
                                <%= f.text_field :phone, class: "form-control", placeholder: "Enter your phone", autocomplete: "off" %>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group spacing-bottom">
          	        <div class="col-sm-6 col-sm-offset-1.5">
          	            <div class="inner-addon left-addon  spacing-top">
          	                <div class="input-group">
          	                    <span class="input-group-addon" id="basic-addon1">
          	                        <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>
          	                    </span>
                                <%= f.file_field :avatar, required: true %>
          	                </div>
          	            </div>
          	        </div>
          	    </div>
              </div>

                <div class="form-group spacing-bottom">
                    <div class="col-sm-6 col-sm-offset-1.5">
                        <div class="inner-addon left-addon  spacing-top">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">
                                    <span class="glyphicon glyphicon-education" aria-hidden="true"></span>
                                </span>
                                <%= f.collection_select :degree_id, Degree.all, :id, :name %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group spacing-bottom" style="">
                    <div class="col-sm-6 col-sm-offset-1.5">
                        <div class="inner-addon left-addon spacing-top">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">
                                    <span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span>
                                </span>
                                <%= f.text_field :additional_info, class: "form-control", placeholder: "You can use this field for adding some more info about yourself", autocomplete: "off" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="spacing-top" >
                <div class="form-group">
                    <div class="text-center spacing-top">
                        <%= f.submit("Sign Up", class: "btn btn-primary btn-lg") %>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>