config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'job_recommendations', to: 'refugees#job_recommendations'
  get 'my_applications', to: 'refugees#my_applications'

  post 'apply', to: 'refugees#apply'


  resources :refugees
  resources :organizations
  resources :jobs, except: [:new]


  get 'settings', to: 'pages#settings'

  # Sessions
  post 'login-org', to: 'sessions#login_org'
  post 'login-ref', to: 'sessions#login_ref'
  delete 'logout', to: 'sessions#logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  has_many :refugees
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :jobs_skills_links
  has_many :skills, through: :jobs_skills_links

  has_many :refugees_jobs_links
  has_many :refugees, through: :refugees_jobs_links

  belongs_to :organization
end

app/models/jobs_skills_link.rb
class JobsSkillsLink < ActiveRecord::Base
  belongs_to :job
  belongs_to :skill
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :refugees_languages_links
  has_many :refugees, through: :refugees_languages_links
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :jobs

  mount_uploader :avatar, AvatarUploader

  has_secure_password
end

app/models/profession.rb
class Profession < ActiveRecord::Base
  has_many :refugees_professions_links
  has_many :refugees, through: :refugees_professions_links
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :issue, polymorphic: true
end

app/models/refugee.rb
class Refugee < ActiveRecord::Base
  has_many :refugees_professions_links
  has_many :professions, through: :refugees_professions_links

  has_many :refugees_languages_links
  has_many :languages, through: :refugees_languages_links4

  has_many :skills_refugees_links
  has_many :skills, through: :skills_refugees_links

  has_many :refugees_jobs_links
  has_many :jobs, through: :refugees_jobs_links

  has_secure_password

  has_one :degree

  mount_uploader :avatar, AvatarUploader
end

app/models/refugees_jobs_link.rb
class RefugeesJobsLink < ActiveRecord::Base
  belongs_to :refugee
  belongs_to :job
end

app/models/refugees_languages_link.rb
class RefugeesLanguagesLink < ActiveRecord::Base
  belongs_to :refugee
  belongs_to :language
end

app/models/refugees_professions_link.rb
class RefugeesProfessionsLink < ActiveRecord::Base
  belongs_to :refugee
  belongs_to :profession
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :jobs_skills_links
  has_many :jobs, through: :jobs_skills_links

  has_many :skills_refugees_links
  has_many :refugees, through: :skills_refugees_links
end

app/models/skills_refugees_link.rb
class SkillsRefugeesLink < ActiveRecord::Base
  belongs_to :skill
  belongs_to :refugee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
    @refugees = @job.refugees
  end

  def create
    skills = params[:job][:skills]
    @job = Job.new(title: params[:job][:title], description: params[:job][:description], expiration_date: params[:job][:expiration_date], location: params[:job][:location])
    @job.organization_id = session[:org_id]

    if @job.save
      skills.each do |s|
        rel = JobsSkillsLink.new(job_id: @job.id, skill_id: s.to_i)
        rel.save
      end

      redirect_to jobs_path
    else

    end

  end

  private
  def jobs_params
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @hide_nav = true
  end

  def settings

  end

end

app/controllers/refugees_controller.rb
class RefugeesController < ApplicationController


private
  def refugee_params
    params.require(:refugee).permit(:name, :birthday, :gender, :nationality, :address, :email, :phone, :additional_info, :degree_id , :password, :avatar)
  end


public
  def index
    @refugees = Refugee.all
  end

  def job_recommendations
    @refugee = Refugee.find(session[:ref_id])
    @skills = @refugee.skills
    @jobs = []
    @skills.each do |u|
      u.jobs.each do |s|
        if !(@jobs.include? s)
          @jobs << s
        end
      end
    end
    render 'jobs/index'
  end

  def apply
    @refugee = RefugeesJobsLink.new(refugee_id: session[:ref_id], job_id: params[:id]);
    @refugee.save
    redirect_to jobs_path
  end

  def new
    @refugee = Refugee.new()
  end

  def create
    @refugee = Refugee.new(refugee_params)
    if @refugee.save
        redirect_to refugees_path
    else
        render 'new'
    end
  end

  def my_applications
    @refugee = Refugee.find(session[:ref_id])
    @applications = @refugee.jobs
  end

  def show
    @refugee = Refugee.find(params[:id])
    session[:refugee_id] = @refugee.id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login_org
    org = Organization.find_by(email: params[:session][:email])

    if org && org.authenticate(params[:session][:password])
      session[:org_id] = org.id
      session[:ref_id] = nil
      redirect_to jobs_path
    end
  end

  def login_ref
    ref = Refugee.find_by(email: params[:session][:email])

    if ref && ref.authenticate(params[:session][:password])
      session[:ref_id] = ref.id
      session[:org_id] = nil
      redirect_to jobs_path
    end
  end

  def logout
    session[:ref_id]
    session[:org_id]
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/dash.html.erb
<!DOCTYPE html>
<html>

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<script src="../d3.v3.min.js" charset="utf-8"></script>
		<link rel="stylesheet" href="../bootstrap.min.css"/>
		<link rel="stylesheet" href="../axis.css"/>

	</head>

	<body style="background-color:transparent;">

		<div class="row">
		<div class="col-md-2">
		</div>

		  <div class="col-md-3">
		  		<div class="h1">General Statistics</div>
				<h4 class="text" >
		  			Number of Refugees <br><span class="label label-default">9</span>
		  		</h4>
				<br>
				<div class="h1">Other Info</div>
				<h4 class="text">
					Most Spoken Language <br><span class="label label-default">Portuguese</span>
				</h4>
				<br>
				<h4 class="text">
					Most Common Problem <br><span class="label label-default">A</span>
				</h4>
				<br>
				<h4 class="text">
					Number of incomplete profiles  <br><span class="label label-default">6</span>
				</h4>
		</div>
		  <div id="the_chart"><div/>
		</div>

	</body>

  <script src="chart.js" charset="utf-8"></script>

</html>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "refind.png", alt: "ReFind" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to "All Jobs", jobs_path %></li>

        <!-- Organization -->
        <% if session[:org_id] != nil %>
          <li>
            <a href="#" type="button" data-toggle="modal" data-target="#jobModal">Add opportunity</a>
          </li>
        <!-- Refugee -->
        <% else %>
          <li><%= link_to "Recommendations", job_recommendations_path %></li>
          <li><%= link_to "My Applications", my_applications_path %></li>
        <% end %>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Organizations", organizations_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!-- Organization -->
            <% if session[:org_id] != nil %>
              <li><%= link_to "Profile", organization_path(session[:org_id]) %></li>
            <!-- Refugee -->
            <% else %>
              <li><%= link_to "Profile", refugee_path(session[:ref_id])  %></li>
            <% end %>
            <li><%= link_to "Settings", settings_path  %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign Out", logout_path, method: "DELETE" %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackforgood</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'jobs/modal_form' if session[:org_id] != nil %>
    <% if !(defined? @hide_nav) %>
      <%= render 'layouts/navbar' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="homepageStyle">

  <div class="container">

    <div class="row">

      <div class="jumbotron col-md-8 col-md-offset-2" style="margin-top: 6em">
      <h1>Welcome to <%= image_tag "refind.png", alt: "ReFind", size: "250x80" %>!
      </h1>

      <p>Find and post a job or volunteering opportunities.</p>

      <p>Join the movement to break the barriers between refugees and companies!</p>


      <div class="col-md-6 col-md-offset-3">

      <!-- Button trigger modal -->

        <button type="button" class="btn btn-primary btn-lg spacing" data-toggle="modal" data-target="#refModal">
          Refugees
        </button>

        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#orgModal">
          Organizations
        </button>

      </div>

    </div>



      <!-- Modal -->
      <div class="modal fade" id="orgModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h2 class="modal-title" id="myModalLabel">Organizations</h2>
            </div>
            <div class="modal-body">
              <%= form_for(:session, :html => {class: "form-horizontal", role: "form"}, url: login_org_path) do |f| %>
                <div class="form-group">
                  <div class="col-sm-8 col-sm-offset-2">
                    <div class="inner-addon left-addon">
                      <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">
                          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        </span>
                        <%= f.text_field :email, class: "form-control", placeholder: "Enter email", autofocus: true %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-8 col-sm-offset-2">
                    <div class="inner-addon left-addon">
                      <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">
                          <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                        </span>
                        <%= f.password_field :password, class: "form-control", placeholder: "Password", autocomplete: "off" %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="text-center">
                    <%= f.submit("Log in", class: "btn btn-primary btn-lg") %>
                  </div>
                </div>
              <% end %>
            </div>
            <div class="modal-footer">
              <%= link_to "Don't have an account? Sign up!", new_organization_path %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="refModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h2 class="modal-title" id="myModalLabel">Refugees</h2>
          </div>
          <div class="modal-body">
            <%= form_for(:session, :html => {class: "form-horizontal", role: "form"}, url: login_ref_path) do |f| %>
              <div class="form-group">
                <div class="col-sm-8 col-sm-offset-2">
                  <div class="inner-addon left-addon">
                    <div class="input-group">
                      <span class="input-group-addon" id="basic-addon1">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                      </span>
                      <%= f.text_field :email, class: "form-control", placeholder: "Enter email", autofocus: true %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-8 col-sm-offset-2">
                  <div class="inner-addon left-addon">
                    <div class="input-group">
                      <span class="input-group-addon" id="basic-addon1">
                        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                      </span>
                      <%= f.password_field :password, class: "form-control", placeholder: "Password", autocomplete: "off" %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="text-center">
                  <%= f.submit("Log in", class: "btn btn-primary btn-lg") %>
                </div>
              </div>
            <% end %>
          </div>
          <div class="modal-footer">
            <%= link_to "Don't have an account? Sign up!", new_refugee_path, html: {data_no_turbolink: "true"} %></a>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/pages/settings.html.erb
<div class="container">

  
</div>